name: spatial-ast
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python>=3.8,<=3.10
  - pip
  - pip:
      - numba==0.58.1
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchvision==0.15.2
      - timm==0.3.2
      - torchlibrosa
      - tensorboard
      - h5py